package test.exception;

public class ExceptionTest {

	public static void main(String[] args) {
		
		int[] arr = new int[3];
		arr[0]=4;
		arr[1]=7;
		arr[2]=1;
		arr[3]=9;
		
		
	}

}
