package com.sds.testapp.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.ModelAndView;

import com.sds.testapp.domain.Notice;
import com.sds.testapp.exception.NoticeException;
import com.sds.testapp.model.notice.NoticeService;

@Controller
public class NoticeController {
	
	@Autowired
	private NoticeService noticeService;
	
	
	@GetMapping("/notice/list")
	public String getList() {
		
		return "notice/list";    
	}
	
	@GetMapping("/notice/writeform")
	public String getRegistForm() {
		
		return "notice/write";
	}
	
	//글쓰기 요청 처리 
	@PostMapping("/notice/regist")
	public ModelAndView regist(Notice notice) {
		System.out.println("글쓰기 요청");
		noticeService.insert(notice); //3단계: 일 시키기 
		
		ModelAndView mav = new ModelAndView("redirect:/notice/list");
		
		return mav;
	}
	
	//컨트롤러가 보유한 메서드들 중 예외가 발생하는 메서드가 있다면 해당 메서드의 실행부는 해당 라인에서 
	//곧바로 아래의 메서드로 진입하게 됨..
	@ExceptionHandler(NoticeException.class)
	public ModelAndView handle(NoticeException e) {
		//에러 원인 보유한 e 를 가지고, 에러 페이지로 가자 
		ModelAndView mav = new ModelAndView("error/result");
		mav.addObject("e", e);
		return mav;
	}
	
}
















